paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Productos obtenidos satisfactoriamente
          schema:
            type: array
            items:
              $ref: "#/definitions/Product"
        "500":
          description: Error interno del servidor

  /api/products/{productId}:
    get:
      summary: Obtiene un producto por su ID
      tags:
        - Productos
      parameters:
        - name: productId
          in: path
          description: ID del producto a obtener
          required: true
          type: string
      responses:
        "200":
          description: Producto obtenido satisfactoriamente
          schema:
            $ref: "#/definitions/Product"
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor



